### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by colleenkhenry** [kmoskwiak/node-tcp-streaming-server#1]
First off, cool project!

Do you have audio working at all?

Thanks!

**Comment by gnarr** [comment]
You just have to include audio in the ffmpeg stream and add to the codec string.

ffmpeg -re -i input.mp4  -c:v libx264 -profile:v main -g 2 -b:v 2500k -keyint_min 1 -strict experimental -pix_fmt yuv420p -movflags empty_moov+default_base_moof -preset ultrafast -c:a aac -f mp4 tcp://localhost:9090

const mimeCodec = 'video/mp4; codecs="avc1.42C028, mp4a.40.2"';
